### ISSUE TITLE
The item "create a team" is missing

### ISSUE THREAD

**Issue by Vearodev** [azerothcore/mod-1v1-arena#31]
The item "create a team" is missing. There is an item only "Delete team".

After deletion, nothing changes.

If the character has honor or arena points, then it is impossible to create a team. Writes that the team has already been created. But if the honor and arena points are 0, then everything works.

LAST VERSION AC

**Comment by Vearodev** [comment]
If the character has honor or arena points, then it is impossible to create a team. Ono believes that the team has already been established. But if the honor and arena points are 0, then everything works.

**Comment by Shoro2** [comment]
Facing the same problem.
As soon a player has >0 honor or arena points its broken.

You can only enter Skirmish queue. Enter ranked, showing stats or deleting the team doesnt work anymore for them

**Comment by DoctorDam** [comment]
Found the solution on my side. Comment lines 340, 341. And truncate the tables acore_characters.arena_team and acore_characters.arena_team_member.

**Comment by youhuowa** [comment]
same problem
no create team

**Comment by Awixs777** [comment]
same problem
no create team

**Comment by Knindzagxg** [comment]
Try on fresh character.

That issue happens when you create team while GM mode is on. At least that happened for me.

**Comment by Awixs777** [comment]
@Knindzagxg  
No, that's not the reason. Even by creating a new character, on an account with 0 access. If you have more than 1 honor and arena points, it is not possible to create a team.

**Comment by pangolp** [comment]
What is the current status of this issue, has it been resolved or does the problem persist? The module has had some updates, but I don't know if all the issues have been fixed. I look forward to hearing from you. Thank you.

**Comment by Awixs777** [comment]
> What is the current status of this issue, has it been resolved or does the problem persist? The module has had some updates, but I don't know if all the issues have been fixed. I look forward to hearing from you. Thank you.

Tested today. The problem still persists. If the character has an honor, it is impossible to create a team. We'll be grateful for the fix.
[Video](https://drive.google.com/file/d/1SL7aDBE-3dZGI6C36r79dni3CQ7nET8T/view?usp=drive_link)

**Comment by pangolp** [comment]
The truth is that I don't know if I will be able to fix it or not, I just wanted to know if the bug was still there, because there are many issues, from several years ago, and I wanted to clean the repository. If it is fixed, at least from my side, it will be uploaded. Maybe someone fixed it, but didn't share it.

**Comment by pangolp** [comment]
I just compiled, with the latest version of the emulator and the changes recently uploaded to the module, and it should work. At least, what belongs to the module, that is to say the part of 1v1. The rest of the equipment, I don't really know if it works, because I don't have so many people to be able to make tests. I close the ticket, and if the bug persists, please create a new issue attaching information to fix the bug. Thank you.
